## This file (main.sage) was *autogenerated* from the file main.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('main')
_st_.blockbegin()
try:
 Verbose=0
except:
 _st_.goboom(62)
_st_.blockend()
_st_.blockbegin()
try:
 f = (x^2-5*x+6)/(x-4)
except:
 _st_.goboom(3)
_st_.blockend()
_st_.blockbegin()
try:
 f = (x^2-5*x)/(x^2+25)
except:
 _st_.goboom(3)
_st_.blockend()
