
# This file was *autogenerated* from the file polyGenerator.sage
from sage.all_cmdline import *   # import sage library

## This file (PolyGenerator.sage) was *autogenerated* from the file PolyGenerator.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('PolyGenerator')
_st_.endofdoc()

