
# This file was *autogenerated* from the file tex/test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4)
var('x','y','z')
A = Matrix([[x - _sage_const_1  ,_sage_const_1 ,_sage_const_0 ],[y - _sage_const_1  ,_sage_const_1 ,_sage_const_1 ],[z - _sage_const_1  ,_sage_const_1 ,_sage_const_2 ]])
print(A)
print(A.det())

B = Matrix([[_sage_const_2 ,-_sage_const_1 ,_sage_const_5 ],[_sage_const_1 ,-_sage_const_2 ,-_sage_const_4 ],[_sage_const_4 ,-_sage_const_5 ,-_sage_const_3 ]])
print(B.det())

