
# This file was *autogenerated* from the file log.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1001 = Integer(1001); _sage_const_1000 = Integer(1000); _sage_const_5 = Integer(5); _sage_const_1p001 = RealNumber('1.001')
for i in xrange(_sage_const_0 ,_sage_const_1001 ):
	print [round(i/_sage_const_1000 ,_sage_const_5 ),round(_sage_const_1p001 **i,_sage_const_5 )]

